// ToolbarEditBoxView.cpp : implementation of the CToolbarEditBoxView class
//

#include "stdafx.h"
#include "ToolbarEditBox.h"

#include "ToolbarEditBoxDoc.h"
#include "ToolbarEditBoxView.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

static const CString strInfo = 
	"This sample illustrates how to use editbox integrated with toolbar control.\r\n\r\n"
	"The following editboxes were added to toolbar:\r\n"
	"* Sample CBCGPToolbarEditBoxButton\r\n"
	"* CBCGPToolbarSpinEditBoxButton - editbox with the spin control\r\n"
	"* CBCGPToolbarEditBoxButton with calculator\r\n\r\n"
	"The project was generated by BCGPApplicationWizard\r\n"
	"Please note //----Exmaple----// comments in the example source code\r\n";

/////////////////////////////////////////////////////////////////////////////
// CToolbarEditBoxView

IMPLEMENT_DYNCREATE(CToolbarEditBoxView, CView)

BEGIN_MESSAGE_MAP(CToolbarEditBoxView, CView)
	//{{AFX_MSG_MAP(CToolbarEditBoxView)
		// NOTE - the ClassWizard will add and remove mapping macros here.
		//    DO NOT EDIT what you see in these blocks of generated code!
	//}}AFX_MSG_MAP
	ON_WM_CONTEXTMENU()
	// Standard printing commands
	ON_COMMAND(ID_FILE_PRINT, CView::OnFilePrint)
	ON_COMMAND(ID_FILE_PRINT_DIRECT, CView::OnFilePrint)
	ON_COMMAND(ID_FILE_PRINT_PREVIEW, OnFilePrintPreview)
END_MESSAGE_MAP()

/////////////////////////////////////////////////////////////////////////////
// CToolbarEditBoxView construction/destruction

CToolbarEditBoxView::CToolbarEditBoxView()
{
	// TODO: add construction code here

}

CToolbarEditBoxView::~CToolbarEditBoxView()
{
}

BOOL CToolbarEditBoxView::PreCreateWindow(CREATESTRUCT& cs)
{
	// TODO: Modify the Window class or styles here by modifying
	//  the CREATESTRUCT cs

	return CView::PreCreateWindow(cs);
}

/////////////////////////////////////////////////////////////////////////////
// CToolbarEditBoxView drawing

void CToolbarEditBoxView::OnDraw(CDC* pDC)
{
	CToolbarEditBoxDoc* pDoc = GetDocument();
	ASSERT_VALID(pDoc);

	const int iOffset = 20;

	CFont* pFontOld = (CFont*) pDC->SelectStockObject (DEFAULT_GUI_FONT);
	ASSERT (pFontOld != NULL);

	CRect rectClient;
	GetClientRect (&rectClient);

	CRect rectText = rectClient;
	rectText.DeflateRect (iOffset, iOffset);
	pDC->DrawText (strInfo, rectText, DT_CALCRECT | DT_WORDBREAK);

	rectText.OffsetRect (	(rectClient.Width () - rectText.Width () - 2 * iOffset) / 2,
							(rectClient.Height () - rectText.Height () - 2 * iOffset) / 2);

	CRect rectFrame = rectText;
	rectFrame.InflateRect (iOffset, iOffset);

	pDC->FillSolidRect (rectFrame, ::GetSysColor (COLOR_INFOBK));
	
	rectFrame.DeflateRect (1, 1);
	pDC->Draw3dRect (rectFrame, ::GetSysColor (COLOR_3DSHADOW), 
					::GetSysColor (COLOR_3DLIGHT));

	rectFrame.DeflateRect (2, 2);
	pDC->Draw3dRect (rectFrame, ::GetSysColor (COLOR_3DSHADOW), 
					::GetSysColor (COLOR_3DLIGHT));

	pDC->SetTextColor (::GetSysColor (COLOR_INFOTEXT));
	pDC->SetBkMode (TRANSPARENT);

	pDC->DrawText (strInfo, rectText, DT_WORDBREAK);

	pDC->SelectObject (pFontOld);
}

/////////////////////////////////////////////////////////////////////////////
// CToolbarEditBoxView printing

void CToolbarEditBoxView::OnFilePrintPreview() 
{
	BCGPPrintPreview (this);
}

BOOL CToolbarEditBoxView::OnPreparePrinting(CPrintInfo* pInfo)
{
	// default preparation
	return DoPreparePrinting(pInfo);
}

void CToolbarEditBoxView::OnBeginPrinting(CDC* /*pDC*/, CPrintInfo* /*pInfo*/)
{
	// TODO: add extra initialization before printing
}

void CToolbarEditBoxView::OnEndPrinting(CDC* /*pDC*/, CPrintInfo* /*pInfo*/)
{
	// TODO: add cleanup after printing
}

/////////////////////////////////////////////////////////////////////////////
// CToolbarEditBoxView diagnostics

#ifdef _DEBUG
void CToolbarEditBoxView::AssertValid() const
{
	CView::AssertValid();
}

void CToolbarEditBoxView::Dump(CDumpContext& dc) const
{
	CView::Dump(dc);
}

CToolbarEditBoxDoc* CToolbarEditBoxView::GetDocument() // non-debug version is inline
{
	ASSERT(m_pDocument->IsKindOf(RUNTIME_CLASS(CToolbarEditBoxDoc)));
	return (CToolbarEditBoxDoc*)m_pDocument;
}
#endif //_DEBUG

/////////////////////////////////////////////////////////////////////////////
// CToolbarEditBoxView message handlers

void CToolbarEditBoxView::OnContextMenu(CWnd*, CPoint point)
{
	theApp.ShowPopupMenu (IDR_CONTEXT_MENU, point, this);
}
