//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by BCGPMSOffice2007Demo.rc
//
#define IDB_BUTTONS                     100
#define IDB_INSERT                      101
#define IDB_INSERTLARGE                 102
#define IDB_INSERTLINK                  103
#define IDB_INSERTLINKLARGE             104
#define IDB_LARGEBUTTONS                105
#define IDB_MAILINGS                    106
#define IDD_POPULAR_PAGE                106
#define IDB_MAILINGSLARGE               107
#define IDD_RES_PAGE                    107
#define IDB_MAIN                        108
#define IDB_PAGELAYOUT                  109
#define IDB_PAGELAYOUTLARGE             110
#define IDB_REFERENCES                  111
#define IDB_REFERENCESLARGE             112
#define IDB_TOOLBAR256                  113
#define IDB_VIEW                        114
#define IDB_VIEWLARGE                   115
#define IDB_WRITE                       116
#define IDB_WRITELARGE                  117
#define IDD_ABOUTBOX                    118
#define IDP_FAILED_TO_CREATE            119
#define IDP_OLE_INIT_FAILED             120
#define IDR_BRINGTOFRONT                121
#define IDR_CNTR_INPLACE                122
#define IDR_CONTEXT_MENU                123
#define IDR_FILE_MENU                   124
#define IDR_FONT                        125
#define IDR_FONTCASE_MENU               126
#define IDR_INSERT_COVERPAGE_MENU       127
#define IDR_MAINFRAME                   128
#define IDR_INSERT_FOOTER_MENU          129
#define IDR_INSERT_HEADER_MENU          130
#define IDR_INSERT_PAGENUMBERS_MENU     131
#define IDR_INSERT_PICTURE_MENU         132
#define IDR_INSERT_SHAPES_MENU          133
#define IDR_MAIL_MERGE_MENU             134
#define IDR_MAIL_RECIPIENTS_MENU        135
#define IDR_MAILMERGE_MENU              136
#define IDR_PAGELAYOUT_BRINGTOFRONT     137
#define IDR_PAGELAYOUT_COLORS           138
#define IDR_PAGELAYOUT_COLUMNS          139
#define IDR_PAGELAYOUT_EFFECTS          140
#define IDR_PAGELAYOUT_MARGINS          141
#define IDR_PAGELAYOUT_ORIENTATION      142
#define IDR_PAGELAYOUT_SENDTOBACK       143
#define IDR_PAGELAYOUT_TEXTWRAPPING     144
#define IDR_PAGELAYOUT_THEMES           145
#define IDR_PARA_BULLETS_MENU           146
#define IDR_PARA_LINESPACING_MENU       147
#define IDR_PARA_MULTILIST_MENU         148
#define IDR_PARA_NUMBERING_MENU         149
#define IDR_PARAGRAPH                   150
#define IDR_PASTE_MENU                  151
#define IDR_POPUP_TOOLBAR               152
#define IDR_REFERENCES_ADDTEXT          153
#define IDR_REFERENCES_INSERTCITATION   154
#define IDB_VIEWPAT_1                   154
#define IDR_REFERENCES_NEXTFOOTNOTE     155
#define IDB_VIEWPAT_2                   155
#define IDR_RIBBONTYPE                  156
#define IDB_VIEWPAT_3                   156
#define IDR_SELECT_MENU                 157
#define IDB_VIEWPAT_4                   157
#define IDR_SELECTRECIPIENTS_MENU       158
#define IDD_QA_CUSTOMIZE                158
#define IDR_SENDTOBACK                  159
#define IDR_STYLE_MENU                  160
#define IDR_STYLECHANGE_MENU            161
#define IDR_TABLE_MENU                  162
#define IDB_SHAPE7                      162
#define IDR_THEME_MENU                  163
#define IDB_SHAPE1                      163
#define IDR_QUICK_ACCESS_MENU           164
#define IDB_SHAPE2                      164
#define IDR_THEME_MENU_STATIC           164
#define IDB_TOOLTIP_FONTDLG             165
#define IDB_TOOLTIP_PARAGRAPH           166
#define IDB_TOOLTIP_CLIPBOARD           167
#define IDR_BCGPMSTYPE                  168
#define IDB_SHAPE6                      168
#define IDB_FILELARGE                   169
#define IDB_FILESMALL                   170
#define IDB_STYLES                      171
#define IDB_SHAPE3                      172
#define IDB_SHAPE4                      173
#define IDB_SHAPE5                      174
#define IDB_PICTURE                     175
#define IDB_CHART                       176
#define IDB_TABLE                       177
#define IDB_PICTURE_FORMAT              178
#define IDB_PICTURE_FORMATLARGE         179
#define IDB_CHART_DESIGN                180
#define IDB_CHART_DESIGNLARGE           181
#define IDB_CHART_LAYOUT                182
#define IDB_CHART_LAYOUTLARGE           183
#define IDB_CHART_FORMAT                184
#define IDB_CHART_FORMATLARGE           185
#define IDB_LAYOUT                      186
#define IDI_REFRESH                     186
#define IDB_SPELL                       187
#define IDI_SPELL                       187
#define IDB_TOOLTIP_MAIN                188
#define IDB_BULLETS                     189
#define IDB_NUM                         190
#define IDB_OPTIONS                     192
#define IDB_BULLETS_RECENT              199
#define IDB_HEADERPAT_1                 200
#define IDB_HEADERPAT_2                 201
#define IDB_HEADERPAT_3                 202
#define IDB_HEADERPAT_4                 203
#define IDC_COMPANY_URL                 1000
#define IDC_SHOW_FLOATY                 1005
#define IDC_SHOW_DEV_TAB                1006
#define IDC_COLOR_SCHEME                1007
#define IDC_SCREENTIP_STYLE             1008
#define IDC_HOME                        1008
#define IDC_CONTACT                     1009
#define IDC_PRODUCT                     1010
#define IDC_SUPPORT                     1011
#define IDC_CATEGORY_COMBO              1042
#define IDC_COMMANDS_LIST               1043
#define IDC_ADD                         1045
#define IDC_REMOVE                      1046
#define IDC_QA_COMMANDS                 1048
#define ID_ACADEMIC                     32770
#define ID_ADDNEWPLACEHOLDER            32771
#define ID_ADDNEWSOURCE                 32772
#define ID_ATRIUM                       32773
#define ID_BEHINDTEXT                   32774
#define ID_BRINGFORWARD                 32775
#define ID_BRINGINFRONTOFTEXT           32776
#define ID_BRINGTOFRONT                 32777
#define ID_BROWSEFORTHEMES              32778
#define ID_FILE_MAIL                    32778
#define ID_CANCEL_EDIT_CNTR             32779
#define ID_CAPITALIZE                   32780
#define ID_STATUSBAR_LINE               32780
#define ID_CIVIC                        32781
#define ID_STATUSBAR_COLUMN             32781
#define ID_CREATENEWTHEMECOLORS         32782
#define ID_STATUSBAR_PROGRESS           32782
#define ID_CUSTOMMARGINS                32783
#define ID_FILE_FAX                     32783
#define ID_EDIT_COPYFORMAT              32784
#define ID_EDITWRAPPOINTS               32785
#define ID_FILE_DOCMANAGE_SERVER        32785
#define ID_FONT_BOLD                    32786
#define ID_FONT_CHANGECASE              32787
#define ID_FONT_CLEARFORMAT             32788
#define ID_FONT_COLOR                   32789
#define ID_FONT_FONT                    32790
#define ID_FONT_FONTSIZE                32791
#define ID_FONT_GROWFONT                32792
#define ID_FONT_ITALIC                  32793
#define ID_FONT_SHRINK                  32794
#define ID_FONT_STRIKETHROUGH           32795
#define ID_FONT_SUBSCRIPT               32796
#define ID_FONT_SUPERSCRIPT             32797
#define ID_FONT_TEXTHIGHLIGHT           32798
#define ID_FONT_UNDERLINE               32799
#define ID_INFRONTOFTEXT                32800
#define ID_FILE_DOCWORKSPACE            32800
#define ID_INLINEWITHTEXT               32801
#define ID_FILE_FINISH                  32801
#define ID_INSERT_BLACKPAGE             32802
#define ID_INSERT_BOOKMARK              32803
#define ID_INSERT_BOTTOMOFPAGE          32804
#define ID_INSERT_CHART                 32805
#define ID_INSERT_CLIPART               32806
#define ID_INSERT_CONVERTTOTABLE        32807
#define ID_FILE_SHARE                   32807
#define ID_INSERT_COVERPAGE             32808
#define ID_INSERT_DATETIME              32809
#define ID_INSERT_DIAGRAM               32810
#define ID_GROUP_SHORTCUTS              32811
#define ID_INSERT_DROPCAP               32812
#define ID_INSERT_EDITFOOTER            32813
#define ID_INSERT_EDITHEADER            32814
#define ID_INSERT_EQUATION              32815
#define ID_INSERT_EXCELSPREADSHEET      32816
#define ID_PRINT_LAYOUT                 32816
#define ID_INSERT_FOOTER                32817
#define ID_INSERT_FORMATPAGENUMBERS     32818
#define ID_INSERT_HEADER                32819
#define ID_INSERT_HYPERLINK             32820
#define ID_INSERT_OBJECT                32821
#define ID_INSERT_PAGEBREAK             32822
#define ID_INSERT_PAGEMARGINS           32823
#define ID_INSERT_PAGENUMBER            32824
#define ID_INSERT_PICTURE               32825
#define ID_INSERT_PICTUREFROMSCANER     32826
#define ID_INSERT_QUICKPARTS            32827
#define ID_INSERT_QUICKTABLES           32828
#define ID_FULL_SCREEN_READING          32828
#define ID_INSERT_REFERENCE             32829
#define ID_INSERT_REMOVECURRENTCOVERPAGE 32830
#define ID_INSERT_REMOVEFOOTER          32831
#define ID_INSERT_REMOVEHEADER          32832
#define ID_INSERT_REMOVEPAGENUMBERS     32833
#define ID_INSERT_SAVESELECTIONTOFOOTERGALLERY 32834
#define ID_INSERT_SAVESELECTIONTOHEADERGALLERY 32835
#define ID_INSERT_SAVETOCOVERPAGEGALLERY 32836
#define ID_INSERT_SHAPES                32837
#define ID_INSERT_SHAPESNEW             32838
#define ID_INSERT_SIGNATURELINE         32839
#define ID_INSERT_SYMBOL                32840
#define ID_INSERT_TABLE                 32841
#define ID_INSERT_TEXTBOX               32842
#define ID_INSERT_TOPOFPAGE             32843
#define ID_INSERT_WORDART               32844
#define ID_LANDSCAPE                    32845
#define ID_WEB_LAYOUT                   32845
#define ID_LEFT                         32846
#define ID_DRAFT                        32846
#define ID_LEVEL1                       32847
#define ID_MASTER_DOCUMENT_TOOLS        32847
#define ID_LEVEL2                       32848
#define ID_STATUSBAR_ZOOM_SLIDER        32848
#define ID_LEVEL3                       32849
#define ID_STATUSBAR_ZOOM               32849
#define ID_LOWERCASE                    32850
#define ID_MAILINGS_ADDRESSBLOCK        32851
#define ID_MAILINGS_AUTOCHECHERRORS     32852
#define ID_MAILINGS_CREATE              32853
#define ID_MAILINGS_CREATELABELS        32854
#define ID_MAILINGS_DIRECTORY           32855
#define ID_MAILINGS_EDITRECIPIENTLIST   32856
#define ID_MAILINGS_EMAILMESSAGES       32857
#define ID_MAILINGS_ENVELOPES           32858
#define ID_MAILINGS_ENVELOPS            32859
#define ID_MAILINGS_FINDRECIPIENT       32860
#define ID_MAILINGS_FINISH              32861
#define ID_MAILINGS_FIRSTRECORD         32862
#define ID_MAILINGS_GOTORECORD          32863
#define ID_MAILINGS_GREATINGLINE        32864
#define ID_MAILINGS_HIGHLIGHT           32865
#define ID_MAILINGS_INSERTMERGEDFIELD   32866
#define ID_MAILINGS_LABELS              32867
#define ID_MAILINGS_LASTRECORD          32868
#define ID_MAILINGS_LETTERS             32869
#define ID_MAILINGS_MATCHFIELDS         32870
#define ID_MAILINGS_NEXTRECORD          32871
#define ID_MAILINGS_NORMALDOCUMENT      32872
#define ID_MAILINGS_PREVIOUSRECORD      32873
#define ID_MAILINGS_RULES               32874
#define ID_MAILINGS_SELECTFROMCONTACTS  32875
#define ID_MAILINGS_SELECTFROMOUTLOOKCONTACTS 32876
#define ID_MAILINGS_SELECTRECIPIENTS    32877
#define ID_MAILINGS_STARTMAILMERGE      32878
#define ID_MAILINGS_STEPBYSTEPMAILMERGEWIZARD 32879
#define ID_MAILINGS_TYPENEWLIST         32880
#define ID_MAILINGS_UPDATELABELS        32881
#define ID_MAILINGS_USEEXISTEDLIST      32882
#define ID_MAILINGS_USEEXISTINGLIST     32883
#define ID_MAILINGS_VIEWMERGEDDATA      32884
#define ID_MIRRORED                     32885
#define ID_MORECOLUMNS                  32886
#define ID_NARROW                       32887
#define ID_NEXTENDNOTE                  32888
#define ID_NEXTFOOTNOTE                 32889
#define ID_NORMAL                       32890
#define ID_NOTSHOWNIN                   32891
#define ID_OFFICE                       32892
#define ID_ONE                          32893
#define ID_PAGELAYOUT_ARRANGE_ALIGN     32894
#define ID_PAGELAYOUT_ARRANGE_BRINGTOFRONT 32895
#define ID_PAGELAYOUT_ARRANGE_GROUP     32896
#define ID_PAGELAYOUT_ARRANGE_POSITION  32897
#define ID_PAGELAYOUT_ARRANGE_ROTATE    32898
#define ID_PAGELAYOUT_ARRANGE_SENDTOBACK 32899
#define ID_PAGELAYOUT_ARRANGE_TEXTWRAPPING 32900
#define ID_PAGELAYOUT_PAGEBACKGROUND_PAGEBORDERS 32901
#define ID_PAGELAYOUT_PAGEBACKGROUND_PAGECOLOR 32902
#define ID_PAGELAYOUT_PAGEBACKGROUND_WATERMARK 32903
#define ID_PAGELAYOUT_PAGESETUP_BREAKS  32904
#define ID_PAGELAYOUT_PAGESETUP_COLUMNS 32905
#define ID_PAGELAYOUT_PAGESETUP_HYPHENATION 32906
#define ID_PAGELAYOUT_PAGESETUP_LINENUMBERS 32907
#define ID_PAGELAYOUT_PAGESETUP_MARGINS 32908
#define ID_PAGELAYOUT_PAGESETUP_ORIENTATTION 32909
#define ID_PAGELAYOUT_PAGESETUP_SIZE    32910
#define ID_PAGELAYOUT_THEMES_COLORS     32911
#define ID_PAGELAYOUT_THEMES_EFFECTS    32912
#define ID_PAGELAYOUT_THEMES_FONTS      32913
#define ID_PAGELAYOUT_THEMES_THEMES     32914
#define ID_PARA_ALIGNLEFT               32915
#define ID_PARA_ALIGNRIGHT              32916
#define ID_PARA_BORDER                  32917
#define ID_PARA_BULLETS                 32918
#define ID_PARA_CENTER                  32919
#define ID_PARA_DECREASEINDENT          32920
#define ID_PARA_DEFINENEWBULLET         32921
#define ID_PARA_DEFINENEWLISTSTYLE      32922
#define ID_PARA_DEFINENEWMULTILEVELLIST 32923
#define ID_PARA_DEFINENEWNUMBERFORMAT   32924
#define ID_PARA_ENDLINEMARK             32925
#define ID_PARA_INCREASEINDENT          32926
#define ID_PARA_JUSTIFY                 32927
#define ID_PARA_LINESPACING             32928
#define ID_PARA_LINESPACING1            32929
#define ID_PARA_LINESPACING2            32930
#define ID_PARA_LINESPACING3            32931
#define ID_PARA_LINESPACING4            32932
#define ID_PARA_LINESPACING5            32933
#define ID_PARA_LINESPACINGAFTER        32934
#define ID_PARA_LINESPACINGBEFORE       32935
#define ID_PARA_LINESPACINGMORE         32936
#define ID_PARA_MULTILEVEL              32937
#define ID_PARA_MULTYLEVEL              32938
#define ID_PARA_NUMBERING               32939
#define ID_PARA_SETNUMBERINGVALUE       32940
#define ID_PARA_SHADING                 32941
#define ID_PARA_SORT                    32942
#define ID_PORTRAIT                     32943
#define ID_PREVIOUSENDNOTE              32944
#define ID_PREVIOUSFOOTNOTE             32945
#define ID_REFERENCES_CAPTIONS_CROSSREFERENCE 32946
#define ID_REFERENCES_CAPTIONS_INSERTCAPTION 32947
#define ID_REFERENCES_CAPTIONS_INSERTTOF 32948
#define ID_REFERENCES_CAPTIONS_UPDATETABLE 32949
#define ID_REFERENCES_CB_INSERTBIBLIOGRAPHY 32950
#define ID_REFERENCES_CB_MANAGESOURCES  32951
#define ID_REFERENCES_FOOTNOTES_INSERTENDNOTE 32952
#define ID_REFERENCES_FOOTNOTES_INSERTFOOTNOTE 32953
#define ID_REFERENCES_FOOTNOTES_NEXTFOOTNOTE 32954
#define ID_REFERENCES_FOOTNOTES_SHOWNOTES 32955
#define ID_REFERENCES_INDEX_INSERTINDEX 32956
#define ID_REFERENCES_INDEX_MARKENTRY   32957
#define ID_REFERENCES_INDEX_UPDATEINDEX 32958
#define ID_REFERENCES_TA_INSERTTOA      32959
#define ID_REFERENCES_TA_MARKCITATION   32960
#define ID_REFERENCES_TA_UPDATETABLE    32961
#define ID_REFERENCES_TC_UPDATETABLE    32962
#define ID_RIGHT                        32963
#define ID_SAVECURRENTTHEME             32964
#define ID_SEARCHLIBRARIES              32965
#define ID_SELECTFORMAT                 32966
#define ID_SELECTOBJECTS                32967
#define ID_SENDBACKWARD                 32968
#define ID_SENDBEHINDTEXT               32969
#define ID_SENDTOBACK                   32970
#define ID_SENTENCE                     32971
#define ID_SQUARE                       32972
#define ID_THREE                        32977
#define ID_THROUGH                      32978
#define ID_TIGHT                        32979
#define ID_TOGGLECASE                   32980
#define ID_TOPANDBOTTOM                 32981
#define ID_TWO                          32982
#define ID_UPPERCASE                    32983
#define ID_VIEW_ACTIONBAR               32984
#define ID_VIEW_APPLOOK_2003            32985
#define ID_VIEW_APPLOOK_2007_1          32986
#define ID_VIEW_APPLOOK_2007_2          32987
#define ID_VIEW_APPLOOK_2007_3          32988
#define ID_VIEW_APPLOOK_2007_4          32989
#define ID_VIEW_ARRANGEALL              32990
#define ID_VIEW_COMPARE                 32991
#define ID_VIEW_CUSTOMIZE               32992
#define ID_VIEW_DOCUMENTMAP             32993
#define ID_VIEW_DRAFT                   32994
#define ID_VIEW_FULLSCREEN              32995
#define ID_VIEW_GRIDLINES               32996
#define ID_VIEW_NEWWINDOW               32997
#define ID_VIEW_OUTLINE                 32998
#define ID_VIEW_PRINTLAYOUT             32999
#define ID_VIEW_PROPERTIES              33000
#define ID_VIEW_RESETWINDOW             33001
#define ID_VIEW_RULER                   33002
#define ID_VIEW_SPLIT                   33003
#define ID_VIEW_SWITCHWINDOW            33004
#define ID_VIEW_SYNCSCROLLING           33005
#define ID_VIEW_TOOLBARS                33006
#define ID_VIEW_TRUMBNAILS              33007
#define ID_VIEW_WEBLAYOUT               33008
#define ID_VIEW_ZOOM                    33009
#define ID_WIDE                         33010
#define ID_WRITE_APPLYSTYLES            33011
#define ID_WRITE_CHANGESTYLES           33012
#define ID_WRITE_CLEARFORMATING         33013
#define ID_WRITE_GOTO                   33014
#define ID_WRITE_PASTEASHYPERLINK       33015
#define ID_WRITE_QUICKSTYLES            33016
#define ID_WRITE_RESTOREINITALSTYLE     33017
#define ID_WRITE_RESTORETEMPLATESTYLE   33018
#define ID_WRITE_SAVEDEFAULTSTYLE       33019
#define ID_WRITE_SAVESTYLE              33020
#define ID_WRITE_SAVESTYLESET           33021
#define ID_WRITE_SELECT                 33022
#define ID_WRITE_SELECTALL              33023
#define ID_WRITE_SELECTFORMATING        33024
#define ID_WRITE_CLIPBOARD              33025
#define ID_WRITE_FONT                   33026
#define ID_WRITE_PARAGRAPH              33027
#define ID_WRITE_STYLE                  33028
#define ID_PARA_PAGESETUP               33029
#define ID_QA_TOOLBAR_ON_TOP            33030
#define ID_QA_TOOLBAR_AT_BOTTOM         33031
#define ID_CUSTOMIZE_QUICK_ACCESS_TOOLBAR 33032
#define ID_PICTURE_FORMAT_TOOLS_BRIGHTNESS 33033
#define ID_PICTURE_FORMAT_TOOLS_CONTRAST 33034
#define ID_PICTURE_FORMAT_TOOLS_RECOLOR 33035
#define ID_PICTURE_FORMAT_TOOLS_COMPRESS 33036
#define ID_PICTURE_FORMAT_TOOLS_CHANGE  33037
#define ID_PICTURE_FORMAT_TOOLS_RESET   33038
#define ID_CHART_DESIGN_TYPE_CHANGE     33039
#define ID_CHART_DESIGN_TYPE_SAVETEMPLATE 33040
#define ID_CHART_DESIGN_DATA_SWITCH     33041
#define ID_CHART_DESIGN_DATA_EDIT       33042
#define ID_CHART_DESIGN_DATA_SHOW       33043
#define ID_CHART_LAYOUT_SHAPES_PICTURE  33044
#define ID_CHART_LAYOUT_SHAPES_SHAPES   33045
#define ID_CHART_LAYOUT_SHAPES_TEXTBOX  33046
#define ID_CHART_LAYOUT_LABELS_TITLE    33047
#define ID_CHART_LAYOUT_LABELS_AXIS     33048
#define ID_CHART_LAYOUT_LABELS_LEGEND   33049
#define ID_CHART_LAYOUT_LABELS_DATALABELS 33050
#define ID_CHART_LAYOUT_LABELS_DATATABLE 33051
#define ID_CHART_LAYOUT_AXES_AXES       33052
#define ID_CHART_LAYOUT_AXES_GRIDLINES  33053
#define ID_CHART_FORMAT_CURSEL_FORMAT   33054
#define ID_CHART_FORMAT_CURSEL_RESET    33055
#define ID_CHART_FORMAT_SHAPES_FILL     33056
#define ID_CHART_FORMAT_SHAPES_OUTLINE  33057
#define ID_CHART_FORMAT_SHAPES_EFFECTS  33058
#define ID_STATUSBAR_PAGE               33059
#define ID_STATUSBAR_REFRESH            33060
#define ID_STATUSBAR_SPELL              33061
#define ID_PAGELAYOUT_INDENT_LEFT       33062
#define ID_PAGELAYOUT_INDENT_RIGHT      33063
#define ID_PAGELAYOUT_SPACE_BEFORE      33064
#define ID_PAGELAYOUT_SPACE_AFTER       33065
#define ID_MAIN_BUTTON                  33066
#define ID_INSERT_BULLET_FROM_PALETTE   33067
#define ID_PARA_CHANGE_LIST_LEVEL       33068
#define ID_INSERT_NUMBER_FROM_PALETTE   33069
#define ID_TOOLS_OPTIONS                33070
#define ID_INSERT_DRAWTABLE             33071

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        193
#define _APS_NEXT_COMMAND_VALUE         33072
#define _APS_NEXT_CONTROL_VALUE         1009
#define _APS_NEXT_SYMED_VALUE           1101
#endif
#endif
