// FileDialogDemoView.cpp : implementation of the CFileDialogDemoView class
//

#include "stdafx.h"
#include "FileDialogDemo.h"

#include "FileDialogDemoDoc.h"
#include "FileDialogDemoView.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

static const CString strInfo = 
	"This sample illustrates how to use CBCGPFileDlg class instead of standard CFileDlg.\r\n\r\n"
	"The following features are available:\r\n"
	"* Put a custom logo on the top of dialog\r\n"
	"* New, Existing and Recent tabs\r\n\r\n"
	"The project was generated by BCGPApplicationWizard\r\n"
	"Please note //----Exmaple----// comments in the example source code\r\n";

/////////////////////////////////////////////////////////////////////////////
// CFileDialogDemoView

IMPLEMENT_DYNCREATE(CFileDialogDemoView, CView)

BEGIN_MESSAGE_MAP(CFileDialogDemoView, CView)
	//{{AFX_MSG_MAP(CFileDialogDemoView)
		// NOTE - the ClassWizard will add and remove mapping macros here.
		//    DO NOT EDIT what you see in these blocks of generated code!
	//}}AFX_MSG_MAP
	ON_WM_CONTEXTMENU()
	// Standard printing commands
	ON_COMMAND(ID_FILE_PRINT, CView::OnFilePrint)
	ON_COMMAND(ID_FILE_PRINT_DIRECT, CView::OnFilePrint)
	ON_COMMAND(ID_FILE_PRINT_PREVIEW, OnFilePrintPreview)
END_MESSAGE_MAP()

/////////////////////////////////////////////////////////////////////////////
// CFileDialogDemoView construction/destruction

CFileDialogDemoView::CFileDialogDemoView()
{
	// TODO: add construction code here

}

CFileDialogDemoView::~CFileDialogDemoView()
{
}

BOOL CFileDialogDemoView::PreCreateWindow(CREATESTRUCT& cs)
{
	// TODO: Modify the Window class or styles here by modifying
	//  the CREATESTRUCT cs

	return CView::PreCreateWindow(cs);
}

/////////////////////////////////////////////////////////////////////////////
// CFileDialogDemoView drawing

void CFileDialogDemoView::OnDraw(CDC* pDC)
{
	CFileDialogDemoDoc* pDoc = GetDocument();
	ASSERT_VALID(pDoc);

	const int iOffset = 20;

	CFont* pFontOld = (CFont*) pDC->SelectStockObject (DEFAULT_GUI_FONT);
	ASSERT (pFontOld != NULL);

	CRect rectClient;
	GetClientRect (&rectClient);

	CRect rectText = rectClient;
	rectText.DeflateRect (iOffset, iOffset);
	pDC->DrawText (strInfo, rectText, DT_CALCRECT | DT_WORDBREAK);

	rectText.OffsetRect (	(rectClient.Width () - rectText.Width () - 2 * iOffset) / 2,
							(rectClient.Height () - rectText.Height () - 2 * iOffset) / 2);

	CRect rectFrame = rectText;
	rectFrame.InflateRect (iOffset, iOffset);

	pDC->FillSolidRect (rectFrame, ::GetSysColor (COLOR_INFOBK));
	
	rectFrame.DeflateRect (1, 1);
	pDC->Draw3dRect (rectFrame, ::GetSysColor (COLOR_3DSHADOW), 
					::GetSysColor (COLOR_3DLIGHT));

	rectFrame.DeflateRect (2, 2);
	pDC->Draw3dRect (rectFrame, ::GetSysColor (COLOR_3DSHADOW), 
					::GetSysColor (COLOR_3DLIGHT));

	pDC->SetTextColor (::GetSysColor (COLOR_INFOTEXT));
	pDC->SetBkMode (TRANSPARENT);

	pDC->DrawText (strInfo, rectText, DT_WORDBREAK);

	pDC->SelectObject (pFontOld);
}

/////////////////////////////////////////////////////////////////////////////
// CFileDialogDemoView printing

void CFileDialogDemoView::OnFilePrintPreview() 
{
	BCGPPrintPreview (this);
}

BOOL CFileDialogDemoView::OnPreparePrinting(CPrintInfo* pInfo)
{
	// default preparation
	return DoPreparePrinting(pInfo);
}

void CFileDialogDemoView::OnBeginPrinting(CDC* /*pDC*/, CPrintInfo* /*pInfo*/)
{
	// TODO: add extra initialization before printing
}

void CFileDialogDemoView::OnEndPrinting(CDC* /*pDC*/, CPrintInfo* /*pInfo*/)
{
	// TODO: add cleanup after printing
}

/////////////////////////////////////////////////////////////////////////////
// CFileDialogDemoView diagnostics

#ifdef _DEBUG
void CFileDialogDemoView::AssertValid() const
{
	CView::AssertValid();
}

void CFileDialogDemoView::Dump(CDumpContext& dc) const
{
	CView::Dump(dc);
}

CFileDialogDemoDoc* CFileDialogDemoView::GetDocument() // non-debug version is inline
{
	ASSERT(m_pDocument->IsKindOf(RUNTIME_CLASS(CFileDialogDemoDoc)));
	return (CFileDialogDemoDoc*)m_pDocument;
}
#endif //_DEBUG

/////////////////////////////////////////////////////////////////////////////
// CFileDialogDemoView message handlers

void CFileDialogDemoView::OnContextMenu(CWnd*, CPoint point)
{
	theApp.ShowPopupMenu (IDR_CONTEXT_MENU, point, this);
}
