//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by $$ROOT$$.RC
//
$$IF(PROJTYPE_MDI)
$$IF(MINI_SERVER || FULL_SERVER || CONTAINER_SERVER)
#define IDR_$$DOC$$TYPE_SRVR_IP		4
#define IDR_$$DOC$$TYPE_SRVR_EMB		5
$$ENDIF//MINI_SERVER || FULL_SERVER || CONTAINER_SERVER
$$IF(CONTAINER || CONTAINER_SERVER)
#define IDR_$$DOC$$TYPE_CNTR_IP		6
$$ENDIF//CONTAINER || CONTAINER_SERVER
$$ELSE //MDI
$$IF(MINI_SERVER || FULL_SERVER || CONTAINER_SERVER)
#define IDR_SRVR_INPLACE			4
#define IDR_SRVR_EMBEDDED			5
$$ENDIF//MINI_SERVER || FULL_SERVER || CONTAINER_SERVER
$$IF(CONTAINER || CONTAINER_SERVER)
#define IDR_CNTR_INPLACE			6
$$ENDIF//CONTAINER || CONTAINER_SERVER
$$ENDIF//!MDI
#define IDD_ABOUTBOX				100
$$IF(CFormView || CRecordView || CDaoRecordView || COleDBRecordView)
#define IDD_$$SAFE_ROOT$$_FORM			101
$$ENDIF
$$IF(TOOLBAR_CUSTOMIZATION || CONTAINER || MINI_SERVER || FULL_SERVER || CONTAINER_SERVER || AUTOMATION)
#define IDP_OLE_INIT_FAILED			100
$$IF(MINI_SERVER)
#define IDP_USE_INSERT_OBJECT		101
$$ENDIF
$$IF(CONTAINER || CONTAINER_SERVER)
#define IDP_FAILED_TO_CREATE		102
#define ID_CANCEL_EDIT_CNTR			32768
$$ENDIF
$$IF(MINI_SERVER || FULL_SERVER || CONTAINER_SERVER)
#define ID_CANCEL_EDIT_SRVR			32769
$$ENDIF
$$ENDIF
$$IF(CRecordView || CDaoRecordView || COleDBRecordView)
#define IDP_FAILED_OPEN_DATABASE	103
$$ENDIF
$$IF(SOCKETS)
#define IDP_SOCKETS_INIT_FAILED		104
$$ENDIF //SOCKETS
$$IF(PROJTYPE_EXPLORER)
$$IF(CListView)
#define ID_VIEW_ARRANGE				127
$$ENDIF 
$$ENDIF 
#define IDR_MAINFRAME				128
#define IDR_$$DOC$$TYPE				129
$$IF(CONTEXT_MENU_CUSTOMIZATION)
#define IDR_CONTEXT_MENU			130
$$ENDIF 
$$IF(TOOLBAR_CUSTOMIZATION || TOOLBAR || STATUSBAR)
#define IDR_POPUP_TOOLBAR			131
$$ENDIF 
$$IF(MDI_TAB_GROUPS)
#define IDR_POPUP_MDITABS			132
#define IDR_POPUP_DROP_MDITABS		133
$$ENDIF 

$$IF(WORKSPACEBAR || OUTPUTBAR)
#define IDB_WORKSPACE                147
$$ENDIF 
$$IF(OUTLOOKBAR)
#define IDB_SHORTCUTS				 148
$$IF(OUTLOOK_BACKGROUND)
#define IDB_SHORTCUTS_BKGND			 149
$$ENDIF //OUTLOOK_BACKGROUND
$$ENDIF //OUTLOOKBAR
$$IF(CAPTIONBAR)
#define IDB_CAPTION					150
$$ENDIF //CAPTIONBAR
$$IF(TOOLBAR_256_COLORS)
#define IDB_TOOLBAR256				151
$$ENDIF // TOOLBAR_256_COLORS
$$IF(TOOLBAR_HOT_TRACK)
#define IDB_TOOLBARCOLD256			152
$$ENDIF // TOOLBAR_HOT_TRACK
$$IF(TASKPANE)
#define IDB_TASKS					153
$$ENDIF // TASKPANE
$$IF(TOOLBAR)
#define ID_VIEW_TOOLBARS			32771
$$ENDIF
$$IF(WINDOWS_DLG)
#define IDS_WINDOWS_MANAGER			107
$$ENDIF
#define IDC_COMPANY_URL             1041
$$IF(TOOLBAR_CUSTOMIZATION)
#define ID_VIEW_CUSTOMIZE			32770
$$ENDIF
$$IF(USER_TOOLBAR)
#define ID_VIEW_USER_TOOLBAR1		32793
#define ID_VIEW_USER_TOOLBAR2		32794
#define ID_VIEW_USER_TOOLBAR3		32795
#define ID_VIEW_USER_TOOLBAR4		32796
#define ID_VIEW_USER_TOOLBAR5		32797
#define ID_VIEW_USER_TOOLBAR6		32798
#define ID_VIEW_USER_TOOLBAR7		32799
#define ID_VIEW_USER_TOOLBAR8		32800
#define ID_VIEW_USER_TOOLBAR9		32801
#define ID_VIEW_USER_TOOLBAR10		32802
$$ENDIF
$$IF(WORKSPACEBAR)
#define ID_VIEW_WORKSPACE			32803
#define ID_VIEW_WORKSPACE2			32792
$$ENDIF
$$IF(OUTPUTBAR)
#define ID_VIEW_OUTPUT				32804
$$ENDIF
$$IF(TASKPANE)
#define ID_VIEW_TASKPANE			32827
$$ENDIF
$$IF(USER_TOOLS)
#define ID_TOOLS_ENTRY				32805
#define ID_USER_TOOL1				32806
#define ID_USER_TOOL2				32807
#define ID_USER_TOOL3				32808
#define ID_USER_TOOL4				32809
#define ID_USER_TOOL5				32810
#define ID_USER_TOOL6				32811
#define ID_USER_TOOL7				32812
#define ID_USER_TOOL8				32813
#define ID_USER_TOOL9				32814
#define ID_USER_TOOL10				32815
$$ENDIF
$$IF(CAPTIONBAR)
#define ID_VIEW_CAPTIONBAR			32816
$$ENDIF
$$IF(OUTLOOKBAR)
#define ID_VIEW_OUTLOOKBAR			32817
#define ID_SHORTCUT_1				32818
#define ID_SHORTCUT_2				32819
#define ID_SHORTCUT_3				32820
#define ID_SHORTCUT_4				32821
#define ID_SHORTCUTS_PANE_1			32824
#define ID_SHORTCUTS_PANE_2			32825
#define ID_SHORTCUTS_TREE			32826
$$ENDIF
$$IF(WINDOWS_DLG)
#define ID_WINDOW_MANAGER			32823
$$ENDIF
$$IF(TASKPANE)
#define ID_TASK1					32828
#define ID_TASK2					32829
#define ID_TASK3					32830
#define ID_TASK4					32831
#define ID_TASK5					32832
$$ENDIF

$$IF(VISUAL_MANAGER)
#define ID_VIEW_APPLOOK_2000		32833
#define ID_VIEW_APPLOOK_XP			32834
#define ID_VIEW_APPLOOK_2003		32835
#define ID_VIEW_APPLOOK_WIN_XP		32836
#define ID_VIEW_APPLOOK_VS2005		32837
#define ID_VIEW_APPLOOK_2007		32838
$$ENDIF
$$IF(MDI_TAB_GROUPS)

#define ID_MDI_NEW_VERT_GROUP       32839
#define ID_MDI_NEW_HORZ_TAB_GROUP   32840
#define ID_MDI_MOVE_TO_PREV_GROUP   32841
#define ID_MDI_CANCEL               32842
#define ID_MDI_MOVE_TO_NEXT_GROUP   32843
$$ENDIF

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
$$IF(3D)
#define _APS_3D_CONTROLS			1
$$ENDIF //3D
$$IF(PROJTYPE_DLL || PROJTYPE_OCX)
#define _APS_NEXT_RESOURCE_VALUE	$$START_RES$$
#define _APS_NEXT_CONTROL_VALUE		$$START_RES$$
#define _APS_NEXT_SYMED_VALUE		$$START_RES$$
$$ELSE
#define _APS_NEXT_RESOURCE_VALUE	154
#define _APS_NEXT_CONTROL_VALUE		1042
#define _APS_NEXT_SYMED_VALUE		108
$$ENDIF //(PROJTYPE_DLL || PROJTYPE_OCX)
#define _APS_NEXT_COMMAND_VALUE		32844
#endif
#endif
