//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by [!output PROJECT_NAME].rc
//
[!if APP_TYPE_MDI]
[!if MINI_SERVER || FULL_SERVER || CONTAINER_SERVER]
#define IDR_[!output SAFE_DOC_TYPE_NAME]TYPE_SRVR_IP		4
#define IDR_[!output SAFE_DOC_TYPE_NAME]TYPE_SRVR_EMB		5
[!endif]
[!if CONTAINER || CONTAINER_SERVER]
#define IDR_[!output SAFE_DOC_TYPE_NAME]TYPE_CNTR_IP		6
[!endif]
[!else]
[!if MINI_SERVER || FULL_SERVER || CONTAINER_SERVER]
#define IDR_SRVR_INPLACE			4
#define IDR_SRVR_EMBEDDED			5
[!endif]
[!if CONTAINER || CONTAINER_SERVER]
#define IDR_CNTR_INPLACE			6
[!endif]
[!endif]
#define IDD_ABOUTBOX				100
[!if FORM_VIEW || OLEDB_RECORD_VIEW || ODBC_RECORD_VIEW]
#define IDD_[!output UPPER_CASE_SAFE_PROJECT_IDENTIFIER_NAME]_FORM			101
[!endif]
[!if CONTAINER || CONTAINER_SERVER || MINI_SERVER || FULL_SERVER || AUTOMATION || ACTIVEX_CONTROLS || OLEDB || ACCESSIBILITY]
#define IDP_OLE_INIT_FAILED			100
[!if MINI_SERVER]
#define IDP_USE_INSERT_OBJECT		101
[!endif]
[!if CONTAINER || CONTAINER_SERVER]
#define IDP_FAILED_TO_CREATE		102
#define ID_CANCEL_EDIT_CNTR			32768
[!endif]
[!if MINI_SERVER || FULL_SERVER || CONTAINER_SERVER]
#define ID_CANCEL_EDIT_SRVR			32769
[!endif]
[!endif]
[!if OLEDB_RECORD_VIEW || ODBC_RECORD_VIEW]
#define IDP_FAILED_OPEN_DATABASE	103
[!endif]
[!if SOCKETS]
#define IDP_SOCKETS_INIT_FAILED		104
[!endif]
[!if PROJECT_STYLE_EXPLORER]
[!if LIST_VIEW]
#define ID_VIEW_ARRANGE				127
[!endif] 
[!endif] 
#define IDR_MAINFRAME				128
#define IDR_[!output SAFE_DOC_TYPE_NAME]TYPE				129
[!if CONTEXT_MENU_CUSTOMIZATION]
#define IDR_CONTEXT_MENU			130
[!endif]
[!if DOCKING_TOOLBAR || STATUSBAR]
#define IDR_POPUP_TOOLBAR			131
[!endif]
[!if MDI_TAB_GROUPS]
#define IDR_POPUP_MDITABS			132
#define IDR_POPUP_DROP_MDITABS		133
[!endif]
[!if WORKSPACEBAR]
#define IDB_WORKSPACE                147
[!endif]
[!if OUTLOOKBAR]
#define IDB_SHORTCUTS				 148
[!if OUTLOOK_BACKGROUND]
#define IDB_SHORTCUTS_BKGND			 149
[!endif]
[!endif]
[!if CAPTIONBAR]
#define IDB_CAPTION					150
[!endif]
[!if TOOLBAR_256_COLORS]
#define IDB_TOOLBAR256				151
[!endif]
[!if TOOLBAR_HOT_TRACK]
#define IDB_TOOLBARCOLD256			152
[!endif]
[!if DOCKING_TOOLBAR]
#define IDS_MAIN_TOOLBAR			101
#define ID_VIEW_TOOLBARS			32771
[!endif]
[!if WINDOWS_DLG]
#define IDS_WINDOWS_MANAGER			107
[!endif]
#define IDC_COMPANY_URL             1041
[!if TOOLBAR_CUSTOMIZATION]
#define ID_VIEW_CUSTOMIZE			32770
[!endif]
[!if USER_TOOLBAR]
#define ID_VIEW_USER_TOOLBAR1		32793
#define ID_VIEW_USER_TOOLBAR2		32794
#define ID_VIEW_USER_TOOLBAR3		32795
#define ID_VIEW_USER_TOOLBAR4		32796
#define ID_VIEW_USER_TOOLBAR5		32797
#define ID_VIEW_USER_TOOLBAR6		32798
#define ID_VIEW_USER_TOOLBAR7		32799
#define ID_VIEW_USER_TOOLBAR8		32800
#define ID_VIEW_USER_TOOLBAR9		32801
#define ID_VIEW_USER_TOOLBAR10		32802
[!endif]
[!if WORKSPACEBAR]
#define ID_VIEW_WORKSPACE			32803
#define ID_VIEW_WORKSPACE2			32792
[!endif]
[!if OUTPUTBAR]
#define ID_VIEW_OUTPUT				32804
[!endif]
[!if USER_TOOLS]
#define ID_TOOLS_ENTRY				32805
#define ID_USER_TOOL1				32806
#define ID_USER_TOOL2				32807
#define ID_USER_TOOL3				32808
#define ID_USER_TOOL4				32809
#define ID_USER_TOOL5				32810
#define ID_USER_TOOL6				32811
#define ID_USER_TOOL7				32812
#define ID_USER_TOOL8				32813
#define ID_USER_TOOL9				32814
#define ID_USER_TOOL10				32815
[!endif]
[!if CAPTIONBAR]
#define ID_VIEW_CAPTIONBAR			32816
[!endif]
[!if OUTLOOKBAR]
#define ID_VIEW_OUTLOOKBAR			32817
#define ID_SHORTCUT_1				32818
#define ID_SHORTCUT_2				32819
#define ID_SHORTCUT_3				32820
#define ID_SHORTCUT_4				32821
#define ID_SHORTCUTS_PANE_1			32822
#define ID_SHORTCUTS_PANE_2			32823
#define ID_SHORTCUTS_TREE			32824
[!endif]
[!if WINDOWS_DLG]
#define ID_WINDOW_MANAGER			32825
[!endif]
[!if VISUAL_MANAGER]
#define ID_VIEW_APPLOOK_2000		32826
#define ID_VIEW_APPLOOK_XP			32827
#define ID_VIEW_APPLOOK_2003		32828
#define ID_VIEW_APPLOOK_WIN_XP		32829
#define ID_VIEW_APPLOOK_VS2005		32830
#define ID_VIEW_APPLOOK_2007		32831
[!endif]
[!if MDI_TAB_GROUPS]
#define ID_MDI_NEW_VERT_GROUP       32838
#define ID_MDI_NEW_HORZ_TAB_GROUP   32839
#define ID_MDI_MOVE_TO_PREV_GROUP   32840
#define ID_MDI_CANCEL               32841
#define ID_MDI_MOVE_TO_NEXT_GROUP   32842
[!endif]

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE	153
#define _APS_NEXT_CONTROL_VALUE		1042
#define _APS_NEXT_SYMED_VALUE		108
#define _APS_NEXT_COMMAND_VALUE		32843
#endif
#endif
